
test1:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test1.s -o test1.o
	riscv64-linux-gnu-objcopy -O binary test1.o test1.bin
	rm test1.o

test2:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test2.s -o test2.o
	riscv64-linux-gnu-objcopy -O binary test2.o test2.bin
	rm test2.o

test3:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test3.s -o test3.o
	riscv64-linux-gnu-objcopy -O binary test3.o test3.bin
	rm test3.o

test4:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test4.s -o test4.o
	riscv64-linux-gnu-objcopy -O binary test4.o test4.bin
	rm test4.o

test5:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test5.s -o test5.o
	riscv64-linux-gnu-objcopy -O binary test5.o test5.bin
	rm test5.o

test6:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test6.s -o test6.o
	riscv64-linux-gnu-objcopy -O binary test6.o test6.bin
	rm test6.o


test7:
	riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c test7.s -o test7.o
	riscv64-linux-gnu-objcopy -O binary test7.o test7.bin
	rm test7.o